// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/cache/pb/info.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1c07a25671ff347, []int{0}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

type InfoReply struct {
	// "local" | "shard" | "tiered" — determines which backend detail
	// fields are populated.
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// Seconds since daemon start.
	UptimeSec int64 `protobuf:"varint,2,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	// Wire-handler counters. Always populated regardless of mode.
	Server *ServerStats `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	// Tiered-mode cascade stats. Nil when mode != "tiered".
	Tiered *TieredStats `protobuf:"bytes,4,opt,name=tiered,proto3" json:"tiered,omitempty"`
	// Top-level RocksDB CF properties. Populated in local/shard mode
	// (the daemon's primary rocks.Store); nil in tiered mode because
	// tiered has no single top-level rocks — per-tier rocks properties
	// appear inside TieredStats.tiers[].rocks instead.
	Rocks []*RocksCFStats `protobuf:"bytes,5,rep,name=rocks,proto3" json:"rocks,omitempty"`
	// Direct local/shard backend discriminator and Redis detail.
	BackendType          string      `protobuf:"bytes,6,opt,name=backend_type,json=backendType,proto3" json:"backend_type,omitempty"`
	Redis                *RedisStats `protobuf:"bytes,7,opt,name=redis,proto3" json:"redis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InfoReply) Reset()         { *m = InfoReply{} }
func (m *InfoReply) String() string { return proto.CompactTextString(m) }
func (*InfoReply) ProtoMessage()    {}
func (*InfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1c07a25671ff347, []int{1}
}

func (m *InfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoReply.Unmarshal(m, b)
}
func (m *InfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoReply.Marshal(b, m, deterministic)
}
func (m *InfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoReply.Merge(m, src)
}
func (m *InfoReply) XXX_Size() int {
	return xxx_messageInfo_InfoReply.Size(m)
}
func (m *InfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_InfoReply proto.InternalMessageInfo

func (m *InfoReply) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *InfoReply) GetUptimeSec() int64 {
	if m != nil {
		return m.UptimeSec
	}
	return 0
}

func (m *InfoReply) GetServer() *ServerStats {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *InfoReply) GetTiered() *TieredStats {
	if m != nil {
		return m.Tiered
	}
	return nil
}

func (m *InfoReply) GetRocks() []*RocksCFStats {
	if m != nil {
		return m.Rocks
	}
	return nil
}

func (m *InfoReply) GetBackendType() string {
	if m != nil {
		return m.BackendType
	}
	return ""
}

func (m *InfoReply) GetRedis() *RedisStats {
	if m != nil {
		return m.Redis
	}
	return nil
}

// ServerStats is the daemon-as-server view. A single external RPC
// bumps exactly one of Hits/Misses (for Get/GetShard) or exactly one
// of Fills (for Fill/FillShard success). Distinct from the tier-level
// cascade counts where a single RPC may bump multiple tiers.
type ServerStats struct {
	Hits                 uint64   `protobuf:"varint,1,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses               uint64   `protobuf:"varint,2,opt,name=misses,proto3" json:"misses,omitempty"`
	Fills                uint64   `protobuf:"varint,3,opt,name=fills,proto3" json:"fills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStats) Reset()         { *m = ServerStats{} }
func (m *ServerStats) String() string { return proto.CompactTextString(m) }
func (*ServerStats) ProtoMessage()    {}
func (*ServerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1c07a25671ff347, []int{2}
}

func (m *ServerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStats.Unmarshal(m, b)
}
func (m *ServerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStats.Marshal(b, m, deterministic)
}
func (m *ServerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStats.Merge(m, src)
}
func (m *ServerStats) XXX_Size() int {
	return xxx_messageInfo_ServerStats.Size(m)
}
func (m *ServerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStats.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStats proto.InternalMessageInfo

func (m *ServerStats) GetHits() uint64 {
	if m != nil {
		return m.Hits
	}
	return 0
}

func (m *ServerStats) GetMisses() uint64 {
	if m != nil {
		return m.Misses
	}
	return 0
}

func (m *ServerStats) GetFills() uint64 {
	if m != nil {
		return m.Fills
	}
	return 0
}

type TieredStats struct {
	Tiers                []*TierStats `protobuf:"bytes,1,rep,name=tiers,proto3" json:"tiers,omitempty"`
	Origin               *OriginStats `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TieredStats) Reset()         { *m = TieredStats{} }
func (m *TieredStats) String() string { return proto.CompactTextString(m) }
func (*TieredStats) ProtoMessage()    {}
func (*TieredStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1c07a25671ff347, []int{3}
}

func (m *TieredStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TieredStats.Unmarshal(m, b)
}
func (m *TieredStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TieredStats.Marshal(b, m, deterministic)
}
func (m *TieredStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TieredStats.Merge(m, src)
}
func (m *TieredStats) XXX_Size() int {
	return xxx_messageInfo_TieredStats.Size(m)
}
func (m *TieredStats) XXX_DiscardUnknown() {
	xxx_messageInfo_TieredStats.DiscardUnknown(m)
}

var xxx_messageInfo_TieredStats proto.InternalMessageInfo

func (m *TieredStats) GetTiers() []*TierStats {
	if m != nil {
		return m.Tiers
	}
	return nil
}

func (m *TieredStats) GetOrigin() *OriginStats {
	if m != nil {
		return m.Origin
	}
	return nil
}

// TierStats is one tier's cascade-view counts. Hits = CacheHit +
// CacheHitMiss (the tier answered); Misses = CacheMiss (punt to next);
// Errors = tryTier returned a non-nil err (wire failure, decode error,
// etc.) — distinct from Miss so "peer said no" is not conflated with
// "we failed to ask". Fills = number of fill-aside ops initiated on
// this tier.
//
// Exactly one of rocks/redis/peers/endpoint is populated, per Type:
//   - "embedded": rocks
//   - "redis":    redis
//   - "ec":       peers
//   - "upstream": endpoint
type TierStats struct {
	Type                 string          `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Hits                 uint64          `protobuf:"varint,2,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses               uint64          `protobuf:"varint,3,opt,name=misses,proto3" json:"misses,omitempty"`
	Fills                uint64          `protobuf:"varint,4,opt,name=fills,proto3" json:"fills,omitempty"`
	Rocks                []*RocksCFStats `protobuf:"bytes,5,rep,name=rocks,proto3" json:"rocks,omitempty"`
	Peers                []*PeerStats    `protobuf:"bytes,6,rep,name=peers,proto3" json:"peers,omitempty"`
	Endpoint             string          `protobuf:"bytes,7,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Errors               uint64          `protobuf:"varint,8,opt,name=errors,proto3" json:"errors,omitempty"`
	Redis                *RedisStats     `protobuf:"bytes,9,opt,name=redis,proto3" json:"redis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TierStats) Reset()         { *m = TierStats{} }
func (m *TierStats) String() string { return proto.CompactTextString(m) }
func (*TierStats) ProtoMessage()    {}
func (*TierStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1c07a25671ff347, []int{4}
}

func (m *TierStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TierStats.Unmarshal(m, b)
}
func (m *TierStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TierStats.Marshal(b, m, deterministic)
}
func (m *TierStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TierStats.Merge(m, src)
}
func (m *TierStats) XXX_Size() int {
	return xxx_messageInfo_TierStats.Size(m)
}
func (m *TierStats) XXX_DiscardUnknown() {
	xxx_messageInfo_TierStats.DiscardUnknown(m)
}

var xxx_messageInfo_TierStats proto.InternalMessageInfo

func (m *TierStats) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TierStats) GetHits() uint64 {
	if m != nil {
		return m.Hits
	}
	return 0
}

func (m *TierStats) GetMisses() uint64 {
	if m != nil {
		return m.Misses
	}
	return 0
}

func (m *TierStats) GetFills() uint64 {
	if m != nil {
		return m.Fills
	}
	return 0
}

func (m *TierStats) GetRocks() []*RocksCFStats {
	if m != nil {
		return m.Rocks
	}
	return nil
}

func (m *TierStats) GetPeers() []*PeerStats {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *TierStats) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *TierStats) GetErrors() uint64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

func (m *TierStats) GetRedis() *RedisStats {
	if m != nil {
		return m.Redis
	}
	return nil
}

// OriginStats is the final cascade layer. Origin is a Getter (no
// Fill), so no Fills field. Errors mirrors TierStats.Errors.
type OriginStats struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Hits                 uint64   `protobuf:"varint,2,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses               uint64   `protobuf:"varint,3,opt,name=misses,proto3" json:"misses,omitempty"`
	StorePath            string   `protobuf:"bytes,4,opt,name=store_path,json=storePath,proto3" json:"store_path,omitempty"`
	Endpoint             string   `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Errors               uint64   `protobuf:"varint,6,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginStats) Reset()         { *m = OriginStats{} }
func (m *OriginStats) String() string { return proto.CompactTextString(m) }
func (*OriginStats) ProtoMessage()    {}
func (*OriginStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1c07a25671ff347, []int{5}
}

func (m *OriginStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginStats.Unmarshal(m, b)
}
func (m *OriginStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginStats.Marshal(b, m, deterministic)
}
func (m *OriginStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginStats.Merge(m, src)
}
func (m *OriginStats) XXX_Size() int {
	return xxx_messageInfo_OriginStats.Size(m)
}
func (m *OriginStats) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginStats.DiscardUnknown(m)
}

var xxx_messageInfo_OriginStats proto.InternalMessageInfo

func (m *OriginStats) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OriginStats) GetHits() uint64 {
	if m != nil {
		return m.Hits
	}
	return 0
}

func (m *OriginStats) GetMisses() uint64 {
	if m != nil {
		return m.Misses
	}
	return 0
}

func (m *OriginStats) GetStorePath() string {
	if m != nil {
		return m.StorePath
	}
	return ""
}

func (m *OriginStats) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *OriginStats) GetErrors() uint64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

// PeerStats is per-EC-peer counts. Distinct from tier-level hits
// (which require ≥ dataShards peers to answer for a tier hit); each
// PeerStats row counts the individual peer's shard-level responses.
//
// Misses counts only peer-confirmed StatusMiss replies. Errors counts
// wire/pool failures plus StatusError replies — keeping these separate
// stops transport noise from inflating "cache miss rate". Cancelled
// counts StatusCancelled replies (e.g., after EC.Get early-exits with
// enough hits and cancels the straggler shard fetch). Fills captures
// per-peer write distribution (Maglev should be approximately uniform;
// large deviations indicate routing issues or single-peer write
// failures).
type PeerStats struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Endpoint             string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Hits                 uint64   `protobuf:"varint,3,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses               uint64   `protobuf:"varint,4,opt,name=misses,proto3" json:"misses,omitempty"`
	Fills                uint64   `protobuf:"varint,5,opt,name=fills,proto3" json:"fills,omitempty"`
	Errors               uint64   `protobuf:"varint,6,opt,name=errors,proto3" json:"errors,omitempty"`
	Cancelled            uint64   `protobuf:"varint,7,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerStats) Reset()         { *m = PeerStats{} }
func (m *PeerStats) String() string { return proto.CompactTextString(m) }
func (*PeerStats) ProtoMessage()    {}
func (*PeerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1c07a25671ff347, []int{6}
}

func (m *PeerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerStats.Unmarshal(m, b)
}
func (m *PeerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerStats.Marshal(b, m, deterministic)
}
func (m *PeerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerStats.Merge(m, src)
}
func (m *PeerStats) XXX_Size() int {
	return xxx_messageInfo_PeerStats.Size(m)
}
func (m *PeerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerStats.DiscardUnknown(m)
}

var xxx_messageInfo_PeerStats proto.InternalMessageInfo

func (m *PeerStats) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PeerStats) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *PeerStats) GetHits() uint64 {
	if m != nil {
		return m.Hits
	}
	return 0
}

func (m *PeerStats) GetMisses() uint64 {
	if m != nil {
		return m.Misses
	}
	return 0
}

func (m *PeerStats) GetFills() uint64 {
	if m != nil {
		return m.Fills
	}
	return 0
}

func (m *PeerStats) GetErrors() uint64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

func (m *PeerStats) GetCancelled() uint64 {
	if m != nil {
		return m.Cancelled
	}
	return 0
}

// RocksCFStats mirrors rocks.CFStats. All numeric fields are strings
// because that is how RocksDB's GetProperty returns them — we avoid
// lossy conversion in the daemon and let consumers parse if they want.
type RocksCFStats struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumKeys              string   `protobuf:"bytes,2,opt,name=num_keys,json=numKeys,proto3" json:"num_keys,omitempty"`
	DiskUsage            string   `protobuf:"bytes,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	MemUsage             string   `protobuf:"bytes,4,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RocksCFStats) Reset()         { *m = RocksCFStats{} }
func (m *RocksCFStats) String() string { return proto.CompactTextString(m) }
func (*RocksCFStats) ProtoMessage()    {}
func (*RocksCFStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1c07a25671ff347, []int{7}
}

func (m *RocksCFStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RocksCFStats.Unmarshal(m, b)
}
func (m *RocksCFStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RocksCFStats.Marshal(b, m, deterministic)
}
func (m *RocksCFStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RocksCFStats.Merge(m, src)
}
func (m *RocksCFStats) XXX_Size() int {
	return xxx_messageInfo_RocksCFStats.Size(m)
}
func (m *RocksCFStats) XXX_DiscardUnknown() {
	xxx_messageInfo_RocksCFStats.DiscardUnknown(m)
}

var xxx_messageInfo_RocksCFStats proto.InternalMessageInfo

func (m *RocksCFStats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RocksCFStats) GetNumKeys() string {
	if m != nil {
		return m.NumKeys
	}
	return ""
}

func (m *RocksCFStats) GetDiskUsage() string {
	if m != nil {
		return m.DiskUsage
	}
	return ""
}

func (m *RocksCFStats) GetMemUsage() string {
	if m != nil {
		return m.MemUsage
	}
	return ""
}

type RedisStats struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	GetPoolSize          int64    `protobuf:"varint,2,opt,name=get_pool_size,json=getPoolSize,proto3" json:"get_pool_size,omitempty"`
	SetPoolSize          int64    `protobuf:"varint,3,opt,name=set_pool_size,json=setPoolSize,proto3" json:"set_pool_size,omitempty"`
	GetConnected         int64    `protobuf:"varint,4,opt,name=get_connected,json=getConnected,proto3" json:"get_connected,omitempty"`
	SetConnected         int64    `protobuf:"varint,5,opt,name=set_connected,json=setConnected,proto3" json:"set_connected,omitempty"`
	GetInflight          int64    `protobuf:"varint,6,opt,name=get_inflight,json=getInflight,proto3" json:"get_inflight,omitempty"`
	SetInflight          int64    `protobuf:"varint,7,opt,name=set_inflight,json=setInflight,proto3" json:"set_inflight,omitempty"`
	PoolWaiters          int64    `protobuf:"varint,8,opt,name=pool_waiters,json=poolWaiters,proto3" json:"pool_waiters,omitempty"`
	Draining             int64    `protobuf:"varint,9,opt,name=draining,proto3" json:"draining,omitempty"`
	GetHits              uint64   `protobuf:"varint,10,opt,name=get_hits,json=getHits,proto3" json:"get_hits,omitempty"`
	GetMisses            uint64   `protobuf:"varint,11,opt,name=get_misses,json=getMisses,proto3" json:"get_misses,omitempty"`
	Sets                 uint64   `protobuf:"varint,12,opt,name=sets,proto3" json:"sets,omitempty"`
	Cancelled            uint64   `protobuf:"varint,13,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	LateBytesDrained     uint64   `protobuf:"varint,14,opt,name=late_bytes_drained,json=lateBytesDrained,proto3" json:"late_bytes_drained,omitempty"`
	Reconnects           uint64   `protobuf:"varint,15,opt,name=reconnects,proto3" json:"reconnects,omitempty"`
	ProtocolErrors       uint64   `protobuf:"varint,16,opt,name=protocol_errors,json=protocolErrors,proto3" json:"protocol_errors,omitempty"`
	BackendErrors        uint64   `protobuf:"varint,17,opt,name=backend_errors,json=backendErrors,proto3" json:"backend_errors,omitempty"`
	GetP50Ns             uint64   `protobuf:"varint,18,opt,name=get_p50_ns,json=getP50Ns,proto3" json:"get_p50_ns,omitempty"`
	GetP99Ns             uint64   `protobuf:"varint,19,opt,name=get_p99_ns,json=getP99Ns,proto3" json:"get_p99_ns,omitempty"`
	GetP999Ns            uint64   `protobuf:"varint,20,opt,name=get_p999_ns,json=getP999Ns,proto3" json:"get_p999_ns,omitempty"`
	SetP50Ns             uint64   `protobuf:"varint,21,opt,name=set_p50_ns,json=setP50Ns,proto3" json:"set_p50_ns,omitempty"`
	SetP99Ns             uint64   `protobuf:"varint,22,opt,name=set_p99_ns,json=setP99Ns,proto3" json:"set_p99_ns,omitempty"`
	SetP999Ns            uint64   `protobuf:"varint,23,opt,name=set_p999_ns,json=setP999Ns,proto3" json:"set_p999_ns,omitempty"`
	PoolWaitP99Ns        uint64   `protobuf:"varint,24,opt,name=pool_wait_p99_ns,json=poolWaitP99Ns,proto3" json:"pool_wait_p99_ns,omitempty"`
	Transport            string   `protobuf:"bytes,25,opt,name=transport,proto3" json:"transport,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisStats) Reset()         { *m = RedisStats{} }
func (m *RedisStats) String() string { return proto.CompactTextString(m) }
func (*RedisStats) ProtoMessage()    {}
func (*RedisStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1c07a25671ff347, []int{8}
}

func (m *RedisStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisStats.Unmarshal(m, b)
}
func (m *RedisStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisStats.Marshal(b, m, deterministic)
}
func (m *RedisStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisStats.Merge(m, src)
}
func (m *RedisStats) XXX_Size() int {
	return xxx_messageInfo_RedisStats.Size(m)
}
func (m *RedisStats) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisStats.DiscardUnknown(m)
}

var xxx_messageInfo_RedisStats proto.InternalMessageInfo

func (m *RedisStats) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *RedisStats) GetGetPoolSize() int64 {
	if m != nil {
		return m.GetPoolSize
	}
	return 0
}

func (m *RedisStats) GetSetPoolSize() int64 {
	if m != nil {
		return m.SetPoolSize
	}
	return 0
}

func (m *RedisStats) GetGetConnected() int64 {
	if m != nil {
		return m.GetConnected
	}
	return 0
}

func (m *RedisStats) GetSetConnected() int64 {
	if m != nil {
		return m.SetConnected
	}
	return 0
}

func (m *RedisStats) GetGetInflight() int64 {
	if m != nil {
		return m.GetInflight
	}
	return 0
}

func (m *RedisStats) GetSetInflight() int64 {
	if m != nil {
		return m.SetInflight
	}
	return 0
}

func (m *RedisStats) GetPoolWaiters() int64 {
	if m != nil {
		return m.PoolWaiters
	}
	return 0
}

func (m *RedisStats) GetDraining() int64 {
	if m != nil {
		return m.Draining
	}
	return 0
}

func (m *RedisStats) GetGetHits() uint64 {
	if m != nil {
		return m.GetHits
	}
	return 0
}

func (m *RedisStats) GetGetMisses() uint64 {
	if m != nil {
		return m.GetMisses
	}
	return 0
}

func (m *RedisStats) GetSets() uint64 {
	if m != nil {
		return m.Sets
	}
	return 0
}

func (m *RedisStats) GetCancelled() uint64 {
	if m != nil {
		return m.Cancelled
	}
	return 0
}

func (m *RedisStats) GetLateBytesDrained() uint64 {
	if m != nil {
		return m.LateBytesDrained
	}
	return 0
}

func (m *RedisStats) GetReconnects() uint64 {
	if m != nil {
		return m.Reconnects
	}
	return 0
}

func (m *RedisStats) GetProtocolErrors() uint64 {
	if m != nil {
		return m.ProtocolErrors
	}
	return 0
}

func (m *RedisStats) GetBackendErrors() uint64 {
	if m != nil {
		return m.BackendErrors
	}
	return 0
}

func (m *RedisStats) GetGetP50Ns() uint64 {
	if m != nil {
		return m.GetP50Ns
	}
	return 0
}

func (m *RedisStats) GetGetP99Ns() uint64 {
	if m != nil {
		return m.GetP99Ns
	}
	return 0
}

func (m *RedisStats) GetGetP999Ns() uint64 {
	if m != nil {
		return m.GetP999Ns
	}
	return 0
}

func (m *RedisStats) GetSetP50Ns() uint64 {
	if m != nil {
		return m.SetP50Ns
	}
	return 0
}

func (m *RedisStats) GetSetP99Ns() uint64 {
	if m != nil {
		return m.SetP99Ns
	}
	return 0
}

func (m *RedisStats) GetSetP999Ns() uint64 {
	if m != nil {
		return m.SetP999Ns
	}
	return 0
}

func (m *RedisStats) GetPoolWaitP99Ns() uint64 {
	if m != nil {
		return m.PoolWaitP99Ns
	}
	return 0
}

func (m *RedisStats) GetTransport() string {
	if m != nil {
		return m.Transport
	}
	return ""
}

func init() {
	proto.RegisterType((*InfoRequest)(nil), "cac.cache.v1.InfoRequest")
	proto.RegisterType((*InfoReply)(nil), "cac.cache.v1.InfoReply")
	proto.RegisterType((*ServerStats)(nil), "cac.cache.v1.ServerStats")
	proto.RegisterType((*TieredStats)(nil), "cac.cache.v1.TieredStats")
	proto.RegisterType((*TierStats)(nil), "cac.cache.v1.TierStats")
	proto.RegisterType((*OriginStats)(nil), "cac.cache.v1.OriginStats")
	proto.RegisterType((*PeerStats)(nil), "cac.cache.v1.PeerStats")
	proto.RegisterType((*RocksCFStats)(nil), "cac.cache.v1.RocksCFStats")
	proto.RegisterType((*RedisStats)(nil), "cac.cache.v1.RedisStats")
}

func init() {
	proto.RegisterFile("pkg/cache/pb/info.proto", fileDescriptor_e1c07a25671ff347)
}

var fileDescriptor_e1c07a25671ff347 = []byte{
	// 965 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0x85, 0x44, 0x4a, 0x36, 0x87, 0xb6, 0xe3, 0x6e, 0xd3, 0x98, 0x76, 0xe3, 0xc0, 0x51, 0x51,
	0xc4, 0x87, 0x5a, 0x72, 0xdc, 0xe6, 0xa0, 0x63, 0x93, 0xa6, 0x6d, 0x50, 0x34, 0x11, 0xe8, 0x14,
	0x05, 0x7a, 0x21, 0x28, 0x72, 0x4c, 0x2d, 0x44, 0x72, 0x59, 0xee, 0x2a, 0xad, 0xf2, 0x35, 0x3d,
	0x15, 0xe8, 0xa9, 0xbf, 0xd1, 0xcf, 0x2a, 0x76, 0x76, 0x45, 0x51, 0x8e, 0x02, 0x14, 0xcd, 0x6d,
	0x77, 0xde, 0x9b, 0xd1, 0xbc, 0x37, 0x43, 0x91, 0x70, 0x54, 0xcd, 0xb3, 0x51, 0x12, 0x27, 0x33,
	0x1c, 0x55, 0xd3, 0x11, 0x2f, 0x6f, 0xc4, 0xb0, 0xaa, 0x85, 0x12, 0x6c, 0x2f, 0x89, 0x93, 0x21,
	0x01, 0xc3, 0x37, 0x8f, 0x07, 0xfb, 0xe0, 0xbf, 0x28, 0x6f, 0x44, 0x88, 0xbf, 0x2e, 0x50, 0xaa,
	0xc1, 0x5f, 0x5d, 0xf0, 0xcc, 0xbd, 0xca, 0x97, 0x8c, 0x81, 0x5b, 0x88, 0x14, 0x83, 0xce, 0x59,
	0xe7, 0xdc, 0x0b, 0xe9, 0xcc, 0x4e, 0x01, 0x16, 0x95, 0xe2, 0x05, 0x46, 0x12, 0x93, 0xa0, 0x7b,
	0xd6, 0x39, 0x77, 0x42, 0xcf, 0x44, 0xae, 0x31, 0x61, 0x8f, 0xa1, 0x2f, 0xb1, 0x7e, 0x83, 0x75,
	0xe0, 0x9c, 0x75, 0xce, 0xfd, 0xab, 0xe3, 0x61, 0xfb, 0xe7, 0x86, 0xd7, 0x84, 0x5d, 0xab, 0x58,
	0xc9, 0xd0, 0x12, 0x75, 0x8a, 0xe2, 0x58, 0x63, 0x1a, 0xb8, 0xdb, 0x52, 0x5e, 0x13, 0x66, 0x53,
	0x0c, 0x91, 0x5d, 0x42, 0xaf, 0x16, 0xc9, 0x5c, 0x06, 0xbd, 0x33, 0xe7, 0xdc, 0xbf, 0x3a, 0xd9,
	0xcc, 0x08, 0x35, 0xf4, 0xec, 0x5b, 0x93, 0x62, 0x88, 0xec, 0x21, 0xec, 0x4d, 0xe3, 0x64, 0x8e,
	0x65, 0x1a, 0xa9, 0x65, 0x85, 0x41, 0x9f, 0x24, 0xf9, 0x36, 0xf6, 0x7a, 0x59, 0x21, 0x1b, 0x42,
	0xaf, 0xc6, 0x94, 0xcb, 0x60, 0x87, 0xda, 0x08, 0x6e, 0x15, 0xd5, 0xd0, 0xaa, 0xa4, 0x3e, 0x0f,
	0x5e, 0x81, 0xdf, 0x92, 0xa3, 0xcd, 0x9a, 0x71, 0x25, 0xc9, 0x2c, 0x37, 0xa4, 0x33, 0xbb, 0x07,
	0xfd, 0x82, 0x4b, 0x89, 0x92, 0x8c, 0x72, 0x43, 0x7b, 0x63, 0x77, 0xa1, 0x77, 0xc3, 0xf3, 0x5c,
	0x92, 0x49, 0x6e, 0x68, 0x2e, 0x03, 0x01, 0x7e, 0x4b, 0x2c, 0xbb, 0x80, 0x9e, 0x96, 0xab, 0x2b,
	0x6a, 0x91, 0x47, 0xef, 0xda, 0x62, 0xdb, 0x21, 0x96, 0xb6, 0x51, 0xd4, 0x3c, 0xe3, 0x25, 0xfd,
	0xd6, 0x3b, 0x36, 0xbe, 0x22, 0xcc, 0xda, 0x68, 0x88, 0x83, 0x3f, 0xbb, 0xe0, 0x35, 0x75, 0xb4,
	0x00, 0xb2, 0xc6, 0x4e, 0x5b, 0x9f, 0x1b, 0x51, 0xdd, 0xad, 0xa2, 0x9c, 0xed, 0xa2, 0xdc, 0x96,
	0xa8, 0xff, 0x31, 0xaa, 0x0b, 0xe8, 0x55, 0xa8, 0x75, 0xf7, 0xb7, 0xe9, 0x9e, 0x60, 0xa3, 0x9b,
	0x58, 0xec, 0x04, 0x76, 0xb1, 0x4c, 0x2b, 0xc1, 0x4b, 0x45, 0x93, 0xf3, 0xc2, 0xe6, 0xae, 0x5b,
	0xc5, 0xba, 0x16, 0xb5, 0x0c, 0x76, 0x4d, 0xab, 0xe6, 0xb6, 0x1e, 0xb5, 0xf7, 0xdf, 0x46, 0xfd,
	0x47, 0x07, 0xfc, 0x96, 0x81, 0x1f, 0x6c, 0xd5, 0x29, 0x80, 0x54, 0xa2, 0xc6, 0xa8, 0x8a, 0xd5,
	0x8c, 0xfc, 0xf2, 0x42, 0x8f, 0x22, 0x93, 0x58, 0xcd, 0x36, 0x24, 0xf5, 0xde, 0x2b, 0xa9, 0xdf,
	0x96, 0x34, 0xf8, 0xbb, 0x03, 0x5e, 0xe3, 0x0d, 0x3b, 0x80, 0x2e, 0x4f, 0x6d, 0x7b, 0x5d, 0x9e,
	0x6e, 0x54, 0xec, 0xde, 0xaa, 0xb8, 0x6a, 0xdc, 0xd9, 0xda, 0xb8, 0xbb, 0x7d, 0xc6, 0xbd, 0xf6,
	0x8c, 0xdf, 0xd3, 0x13, 0xbb, 0x0f, 0x5e, 0x12, 0x97, 0x09, 0xe6, 0x39, 0xa6, 0x34, 0x1b, 0x37,
	0x5c, 0x07, 0x06, 0x4b, 0xd8, 0x6b, 0x8f, 0x5f, 0xf7, 0x51, 0xc6, 0x45, 0x63, 0xaa, 0x3e, 0xb3,
	0x63, 0xd8, 0x2d, 0x17, 0x45, 0x34, 0xc7, 0xa5, 0xb4, 0x7d, 0xef, 0x94, 0x8b, 0xe2, 0x07, 0x5c,
	0x92, 0x87, 0x29, 0x97, 0xf3, 0x68, 0x21, 0xe3, 0x0c, 0xa9, 0x79, 0x2f, 0xf4, 0x74, 0xe4, 0x27,
	0x1d, 0x60, 0x9f, 0x82, 0x57, 0x60, 0x61, 0x51, 0xe3, 0xf0, 0x6e, 0x81, 0x05, 0x81, 0x83, 0x7f,
	0xfa, 0x00, 0xeb, 0x29, 0x6f, 0xb8, 0xd3, 0xb9, 0xe5, 0xce, 0x00, 0xf6, 0x33, 0x54, 0x51, 0x25,
	0x44, 0x1e, 0x49, 0xfe, 0x16, 0xed, 0x5f, 0x9e, 0x9f, 0xa1, 0x9a, 0x08, 0x91, 0x5f, 0xf3, 0xb7,
	0xa8, 0x39, 0x72, 0x83, 0xe3, 0x18, 0x8e, 0x6c, 0x71, 0x3e, 0x33, 0x75, 0x12, 0x51, 0x96, 0x98,
	0x28, 0xfb, 0x67, 0xe7, 0x84, 0x7b, 0x19, 0xaa, 0x67, 0xab, 0x98, 0x26, 0xc9, 0x0d, 0x52, 0xcf,
	0x90, 0x64, 0x9b, 0xf4, 0x10, 0x74, 0x52, 0xc4, 0xcb, 0x9b, 0x9c, 0x67, 0x33, 0x45, 0x9e, 0x9b,
	0x86, 0x5e, 0xd8, 0x90, 0xa6, 0xc8, 0x36, 0x65, 0xa7, 0xe9, 0xa7, 0x4d, 0xa1, 0x7e, 0x7f, 0x8b,
	0xb9, 0x42, 0xfb, 0x80, 0x38, 0xa1, 0xaf, 0x63, 0x3f, 0x9b, 0x90, 0xb6, 0x25, 0xad, 0x63, 0x5e,
	0xf2, 0x32, 0xa3, 0x07, 0xc5, 0x09, 0x9b, 0xbb, 0x1e, 0x8c, 0x6e, 0x82, 0x16, 0x07, 0x68, 0xb2,
	0x3b, 0x19, 0xaa, 0xef, 0xf5, 0xee, 0x9c, 0x02, 0x68, 0xc8, 0xee, 0x8f, 0x6f, 0xc6, 0x9e, 0xa1,
	0xfa, 0xd1, 0xac, 0x10, 0x03, 0x57, 0xa2, 0x92, 0xc1, 0x9e, 0x59, 0x37, 0x7d, 0xde, 0x5c, 0x94,
	0xfd, 0x5b, 0x8b, 0xc2, 0xbe, 0x00, 0x96, 0xc7, 0x0a, 0xa3, 0xe9, 0x52, 0xa1, 0x8c, 0xa8, 0x05,
	0x4c, 0x83, 0x03, 0xa2, 0x1d, 0x6a, 0xe4, 0xa9, 0x06, 0xbe, 0x31, 0x71, 0xf6, 0x00, 0xa0, 0x46,
	0xeb, 0xa0, 0x0c, 0xee, 0x10, 0xab, 0x15, 0x61, 0x8f, 0xe0, 0x0e, 0xbd, 0x08, 0x13, 0x91, 0x47,
	0x76, 0x6b, 0x0f, 0x89, 0x74, 0xb0, 0x0a, 0x3f, 0x37, 0xdb, 0xfb, 0x39, 0x1c, 0xac, 0x5e, 0x19,
	0x96, 0xf7, 0x11, 0xf1, 0xf6, 0x6d, 0xf4, 0xf9, 0x6a, 0xc9, 0x49, 0x6e, 0xf5, 0xe4, 0x32, 0x2a,
	0x65, 0xc0, 0x88, 0xa2, 0xbd, 0x99, 0x3c, 0xb9, 0x7c, 0xb9, 0x46, 0xc7, 0x63, 0x8d, 0x7e, 0xbc,
	0x46, 0xc7, 0xe3, 0x97, 0x92, 0x3d, 0x00, 0xdf, 0xa2, 0x04, 0xdf, 0x6d, 0xbc, 0x9a, 0x8c, 0x09,
	0xbf, 0x0f, 0x20, 0xd7, 0xb5, 0x3f, 0x31, 0xd9, 0xb2, 0x55, 0x5b, 0xae, 0x6b, 0xdf, 0x5b, 0xa3,
	0xab, 0xda, 0xb2, 0x55, 0xfb, 0xc8, 0xd4, 0x96, 0x4d, 0xed, 0x47, 0x70, 0xd8, 0x2c, 0xc0, 0xaa,
	0x46, 0x60, 0x04, 0xae, 0x96, 0x60, 0x62, 0x9b, 0xf0, 0x54, 0x1d, 0x97, 0xb2, 0x12, 0xb5, 0x0a,
	0x8e, 0xcd, 0x73, 0xd6, 0x04, 0xae, 0xbe, 0x06, 0x57, 0x7f, 0x30, 0xb0, 0x31, 0x38, 0xdf, 0xa1,
	0x62, 0xb7, 0xde, 0x3a, 0xad, 0x6f, 0x8b, 0x93, 0xa3, 0x6d, 0x50, 0x95, 0x2f, 0x9f, 0x7e, 0xf5,
	0xcb, 0x55, 0xc6, 0xd5, 0x6c, 0x31, 0x1d, 0x26, 0xa2, 0x18, 0xcd, 0x17, 0xb1, 0x8c, 0xeb, 0x0b,
	0x19, 0x97, 0xe9, 0x54, 0xfc, 0x3e, 0x8a, 0x93, 0x04, 0x73, 0xac, 0x63, 0x25, 0xea, 0x51, 0xfb,
	0x93, 0x66, 0xda, 0xa7, 0x71, 0x7d, 0xf9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0x4a, 0x72,
	0xbe, 0xe9, 0x08, 0x00, 0x00,
}
