// Package cac.store.v1 defines the gRPC wire protocol for the
// store-ctl daemon. Clients (manifest-ctl, cache-ctl origin) talk to
// store-ctl through this interface and never touch the underlying
// filesystem or object storage directly.
//
// The service is deliberately small: AdmitWrite fixes an ingest to one
// generation and salt, Get streams bytes out, and Put streams bytes in.
//
// Put is client-streaming with a header-first convention: the first
// PutRequest MUST carry a PutHeader (partition + client-computed key +
// admitted generation + optional size); subsequent PutRequests carry raw
// bytes. The server may SendAndClose early with is_new=false if a matching
// object already exists.
//
// Get is server-streaming: one GetRequest produces one or more
// GetResponse messages with byte chunks, or a NOT_FOUND status on miss.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/store/pb/store.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Partition int32

const (
	Partition_PARTITION_UNSPECIFIED Partition = 0
	Partition_PARTITION_CHUNK       Partition = 1
	Partition_PARTITION_MANIFEST    Partition = 2
	// Arbitrary content-addressed data, isolated from chunk/manifest only
	// by partition. The mechanism is identical: client-computed SHA256 key,
	// generation scope, dedup short-circuit, optional re-hash verify.
	Partition_PARTITION_BLOB Partition = 3
)

// Enum value maps for Partition.
var (
	Partition_name = map[int32]string{
		0: "PARTITION_UNSPECIFIED",
		1: "PARTITION_CHUNK",
		2: "PARTITION_MANIFEST",
		3: "PARTITION_BLOB",
	}
	Partition_value = map[string]int32{
		"PARTITION_UNSPECIFIED": 0,
		"PARTITION_CHUNK":       1,
		"PARTITION_MANIFEST":    2,
		"PARTITION_BLOB":        3,
	}
)

func (x Partition) Enum() *Partition {
	p := new(Partition)
	*p = x
	return p
}

func (x Partition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Partition) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_store_pb_store_proto_enumTypes[0].Descriptor()
}

func (Partition) Type() protoreflect.EnumType {
	return &file_pkg_store_pb_store_proto_enumTypes[0]
}

func (x Partition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Partition.Descriptor instead.
func (Partition) EnumDescriptor() ([]byte, []int) {
	return file_pkg_store_pb_store_proto_rawDescGZIP(), []int{0}
}

type AdmitWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitWriteRequest) Reset() {
	*x = AdmitWriteRequest{}
	mi := &file_pkg_store_pb_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitWriteRequest) ProtoMessage() {}

func (x *AdmitWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_store_pb_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitWriteRequest.ProtoReflect.Descriptor instead.
func (*AdmitWriteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_store_pb_store_proto_rawDescGZIP(), []int{0}
}

type AdmitWriteResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Generation string                 `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	// Clients may combine this with their own extra salt before
	// deriving per-chunk encryption keys.
	Salt          []byte `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitWriteResponse) Reset() {
	*x = AdmitWriteResponse{}
	mi := &file_pkg_store_pb_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitWriteResponse) ProtoMessage() {}

func (x *AdmitWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_store_pb_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitWriteResponse.ProtoReflect.Descriptor instead.
func (*AdmitWriteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_store_pb_store_proto_rawDescGZIP(), []int{1}
}

func (x *AdmitWriteResponse) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *AdmitWriteResponse) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     Partition              `protobuf:"varint,1,opt,name=partition,proto3,enum=cac.store.v1.Partition" json:"partition,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"` // 32 bytes SHA256
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pkg_store_pb_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_store_pb_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_store_pb_store_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetPartition() Partition {
	if x != nil {
		return x.Partition
	}
	return Partition_PARTITION_UNSPECIFIED
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A single chunk of the object's bytes. Multiple GetResponses
	// concatenate in order to form the full object. The client
	// buffers these before returning a materialized store.Blob.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pkg_store_pb_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_store_pb_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_store_pb_store_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*PutRequest_Header
	//	*PutRequest_Data
	Body          isPutRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_pkg_store_pb_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_store_pb_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_store_pb_store_proto_rawDescGZIP(), []int{4}
}

func (x *PutRequest) GetBody() isPutRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PutRequest) GetHeader() *PutHeader {
	if x != nil {
		if x, ok := x.Body.(*PutRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *PutRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Body.(*PutRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isPutRequest_Body interface {
	isPutRequest_Body()
}

type PutRequest_Header struct {
	Header *PutHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"` // first message only
}

type PutRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // subsequent messages
}

func (*PutRequest_Header) isPutRequest_Body() {}

func (*PutRequest_Data) isPutRequest_Body() {}

type PutHeader struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Partition Partition              `protobuf:"varint,1,opt,name=partition,proto3,enum=cac.store.v1.Partition" json:"partition,omitempty"`
	// 32-byte SHA256 of the full object bytes, computed by the
	// client. The server uses this to resolve the target path
	// immediately (enabling the dedup short-circuit) and
	// optionally re-hashes the streamed bytes to verify the
	// client's claim (per-daemon config).
	Key        []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Generation string `protobuf:"bytes,3,opt,name=generation,proto3" json:"generation,omitempty"`
	// Presence matters: zero is a known empty payload, while absence means
	// the sender did not provide an expected size.
	Size          *uint64 `protobuf:"varint,4,opt,name=size,proto3,oneof" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutHeader) Reset() {
	*x = PutHeader{}
	mi := &file_pkg_store_pb_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutHeader) ProtoMessage() {}

func (x *PutHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_store_pb_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutHeader.ProtoReflect.Descriptor instead.
func (*PutHeader) Descriptor() ([]byte, []int) {
	return file_pkg_store_pb_store_proto_rawDescGZIP(), []int{5}
}

func (x *PutHeader) GetPartition() Partition {
	if x != nil {
		return x.Partition
	}
	return Partition_PARTITION_UNSPECIFIED
}

func (x *PutHeader) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutHeader) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *PutHeader) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type PutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// false means dedup hit: the key already existed on the server
	// and no new file was written. true means a new file was
	// created.
	IsNew         bool `protobuf:"varint,1,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_pkg_store_pb_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_store_pb_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_store_pb_store_proto_rawDescGZIP(), []int{6}
}

func (x *PutResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

var File_pkg_store_pb_store_proto protoreflect.FileDescriptor

const file_pkg_store_pb_store_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/store/pb/store.proto\x12\fcac.store.v1\"\x13\n" +
	"\x11AdmitWriteRequest\"H\n" +
	"\x12AdmitWriteResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\tR\n" +
	"generation\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\fR\x04salt\"U\n" +
	"\n" +
	"GetRequest\x125\n" +
	"\tpartition\x18\x01 \x01(\x0e2\x17.cac.store.v1.PartitionR\tpartition\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"!\n" +
	"\vGetResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"]\n" +
	"\n" +
	"PutRequest\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x17.cac.store.v1.PutHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x06\n" +
	"\x04body\"\x96\x01\n" +
	"\tPutHeader\x125\n" +
	"\tpartition\x18\x01 \x01(\x0e2\x17.cac.store.v1.PartitionR\tpartition\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\tR\n" +
	"generation\x12\x17\n" +
	"\x04size\x18\x04 \x01(\x04H\x00R\x04size\x88\x01\x01B\a\n" +
	"\x05_size\"$\n" +
	"\vPutResponse\x12\x15\n" +
	"\x06is_new\x18\x01 \x01(\bR\x05isNew*g\n" +
	"\tPartition\x12\x19\n" +
	"\x15PARTITION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPARTITION_CHUNK\x10\x01\x12\x16\n" +
	"\x12PARTITION_MANIFEST\x10\x02\x12\x12\n" +
	"\x0ePARTITION_BLOB\x10\x032\xd4\x01\n" +
	"\x05Store\x12O\n" +
	"\n" +
	"AdmitWrite\x12\x1f.cac.store.v1.AdmitWriteRequest\x1a .cac.store.v1.AdmitWriteResponse\x12<\n" +
	"\x03Get\x12\x18.cac.store.v1.GetRequest\x1a\x19.cac.store.v1.GetResponse0\x01\x12<\n" +
	"\x03Put\x12\x18.cac.store.v1.PutRequest\x1a\x19.cac.store.v1.PutResponse(\x01B4Z2github.com/kuasar-sandbox/accelerator/pkg/store/pbb\x06proto3"

var (
	file_pkg_store_pb_store_proto_rawDescOnce sync.Once
	file_pkg_store_pb_store_proto_rawDescData []byte
)

func file_pkg_store_pb_store_proto_rawDescGZIP() []byte {
	file_pkg_store_pb_store_proto_rawDescOnce.Do(func() {
		file_pkg_store_pb_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_store_pb_store_proto_rawDesc), len(file_pkg_store_pb_store_proto_rawDesc)))
	})
	return file_pkg_store_pb_store_proto_rawDescData
}

var file_pkg_store_pb_store_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_store_pb_store_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_store_pb_store_proto_goTypes = []any{
	(Partition)(0),             // 0: cac.store.v1.Partition
	(*AdmitWriteRequest)(nil),  // 1: cac.store.v1.AdmitWriteRequest
	(*AdmitWriteResponse)(nil), // 2: cac.store.v1.AdmitWriteResponse
	(*GetRequest)(nil),         // 3: cac.store.v1.GetRequest
	(*GetResponse)(nil),        // 4: cac.store.v1.GetResponse
	(*PutRequest)(nil),         // 5: cac.store.v1.PutRequest
	(*PutHeader)(nil),          // 6: cac.store.v1.PutHeader
	(*PutResponse)(nil),        // 7: cac.store.v1.PutResponse
}
var file_pkg_store_pb_store_proto_depIdxs = []int32{
	0, // 0: cac.store.v1.GetRequest.partition:type_name -> cac.store.v1.Partition
	6, // 1: cac.store.v1.PutRequest.header:type_name -> cac.store.v1.PutHeader
	0, // 2: cac.store.v1.PutHeader.partition:type_name -> cac.store.v1.Partition
	1, // 3: cac.store.v1.Store.AdmitWrite:input_type -> cac.store.v1.AdmitWriteRequest
	3, // 4: cac.store.v1.Store.Get:input_type -> cac.store.v1.GetRequest
	5, // 5: cac.store.v1.Store.Put:input_type -> cac.store.v1.PutRequest
	2, // 6: cac.store.v1.Store.AdmitWrite:output_type -> cac.store.v1.AdmitWriteResponse
	4, // 7: cac.store.v1.Store.Get:output_type -> cac.store.v1.GetResponse
	7, // 8: cac.store.v1.Store.Put:output_type -> cac.store.v1.PutResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_store_pb_store_proto_init() }
func file_pkg_store_pb_store_proto_init() {
	if File_pkg_store_pb_store_proto != nil {
		return
	}
	file_pkg_store_pb_store_proto_msgTypes[4].OneofWrappers = []any{
		(*PutRequest_Header)(nil),
		(*PutRequest_Data)(nil),
	}
	file_pkg_store_pb_store_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_store_pb_store_proto_rawDesc), len(file_pkg_store_pb_store_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_store_pb_store_proto_goTypes,
		DependencyIndexes: file_pkg_store_pb_store_proto_depIdxs,
		EnumInfos:         file_pkg_store_pb_store_proto_enumTypes,
		MessageInfos:      file_pkg_store_pb_store_proto_msgTypes,
	}.Build()
	File_pkg_store_pb_store_proto = out.File
	file_pkg_store_pb_store_proto_goTypes = nil
	file_pkg_store_pb_store_proto_depIdxs = nil
}
