// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/store/pb/store.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Partition int32

const (
	Partition_PARTITION_UNSPECIFIED Partition = 0
	Partition_PARTITION_CHUNK       Partition = 1
	Partition_PARTITION_MANIFEST    Partition = 2
	// Arbitrary content-addressed data, isolated from chunk/manifest only
	// by partition. The mechanism is identical: client-computed SHA256 key,
	// generation scope, dedup short-circuit, optional re-hash verify.
	Partition_PARTITION_BLOB Partition = 3
)

var Partition_name = map[int32]string{
	0: "PARTITION_UNSPECIFIED",
	1: "PARTITION_CHUNK",
	2: "PARTITION_MANIFEST",
	3: "PARTITION_BLOB",
}

var Partition_value = map[string]int32{
	"PARTITION_UNSPECIFIED": 0,
	"PARTITION_CHUNK":       1,
	"PARTITION_MANIFEST":    2,
	"PARTITION_BLOB":        3,
}

func (x Partition) String() string {
	return proto.EnumName(Partition_name, int32(x))
}

func (Partition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_80e9d5d919fe214b, []int{0}
}

type GetSaltRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSaltRequest) Reset()         { *m = GetSaltRequest{} }
func (m *GetSaltRequest) String() string { return proto.CompactTextString(m) }
func (*GetSaltRequest) ProtoMessage()    {}
func (*GetSaltRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e9d5d919fe214b, []int{0}
}

func (m *GetSaltRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSaltRequest.Unmarshal(m, b)
}
func (m *GetSaltRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSaltRequest.Marshal(b, m, deterministic)
}
func (m *GetSaltRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSaltRequest.Merge(m, src)
}
func (m *GetSaltRequest) XXX_Size() int {
	return xxx_messageInfo_GetSaltRequest.Size(m)
}
func (m *GetSaltRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSaltRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSaltRequest proto.InternalMessageInfo

type GetSaltResponse struct {
	// Clients may combine this with their own extra salt before
	// deriving per-chunk encryption keys.
	Salt                 []byte   `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSaltResponse) Reset()         { *m = GetSaltResponse{} }
func (m *GetSaltResponse) String() string { return proto.CompactTextString(m) }
func (*GetSaltResponse) ProtoMessage()    {}
func (*GetSaltResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e9d5d919fe214b, []int{1}
}

func (m *GetSaltResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSaltResponse.Unmarshal(m, b)
}
func (m *GetSaltResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSaltResponse.Marshal(b, m, deterministic)
}
func (m *GetSaltResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSaltResponse.Merge(m, src)
}
func (m *GetSaltResponse) XXX_Size() int {
	return xxx_messageInfo_GetSaltResponse.Size(m)
}
func (m *GetSaltResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSaltResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSaltResponse proto.InternalMessageInfo

func (m *GetSaltResponse) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type GetRequest struct {
	Partition            Partition `protobuf:"varint,1,opt,name=partition,proto3,enum=cac.store.v1.Partition" json:"partition,omitempty"`
	Key                  []byte    `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e9d5d919fe214b, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetPartition() Partition {
	if m != nil {
		return m.Partition
	}
	return Partition_PARTITION_UNSPECIFIED
}

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	// A single chunk of the object's bytes. Multiple GetResponses
	// concatenate in order to form the full object. The client
	// buffers these before returning a materialized store.Blob.
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e9d5d919fe214b, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PutRequest struct {
	// Types that are valid to be assigned to Body:
	//	*PutRequest_Header
	//	*PutRequest_Data
	Body                 isPutRequest_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e9d5d919fe214b, []int{4}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

type isPutRequest_Body interface {
	isPutRequest_Body()
}

type PutRequest_Header struct {
	Header *PutHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type PutRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*PutRequest_Header) isPutRequest_Body() {}

func (*PutRequest_Data) isPutRequest_Body() {}

func (m *PutRequest) GetBody() isPutRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *PutRequest) GetHeader() *PutHeader {
	if x, ok := m.GetBody().(*PutRequest_Header); ok {
		return x.Header
	}
	return nil
}

func (m *PutRequest) GetData() []byte {
	if x, ok := m.GetBody().(*PutRequest_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PutRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PutRequest_Header)(nil),
		(*PutRequest_Data)(nil),
	}
}

type PutHeader struct {
	Partition Partition `protobuf:"varint,1,opt,name=partition,proto3,enum=cac.store.v1.Partition" json:"partition,omitempty"`
	// 32-byte SHA256 of the full object bytes, computed by the
	// client. The server uses this to resolve the target path
	// immediately (enabling the dedup short-circuit) and
	// optionally re-hashes the streamed bytes to verify the
	// client's claim (per-daemon config).
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutHeader) Reset()         { *m = PutHeader{} }
func (m *PutHeader) String() string { return proto.CompactTextString(m) }
func (*PutHeader) ProtoMessage()    {}
func (*PutHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e9d5d919fe214b, []int{5}
}

func (m *PutHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutHeader.Unmarshal(m, b)
}
func (m *PutHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutHeader.Marshal(b, m, deterministic)
}
func (m *PutHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutHeader.Merge(m, src)
}
func (m *PutHeader) XXX_Size() int {
	return xxx_messageInfo_PutHeader.Size(m)
}
func (m *PutHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_PutHeader.DiscardUnknown(m)
}

var xxx_messageInfo_PutHeader proto.InternalMessageInfo

func (m *PutHeader) GetPartition() Partition {
	if m != nil {
		return m.Partition
	}
	return Partition_PARTITION_UNSPECIFIED
}

func (m *PutHeader) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type PutResponse struct {
	// false means dedup hit: the key already existed on the server
	// and no new file was written. true means a new file was
	// created.
	IsNew                bool     `protobuf:"varint,1,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e9d5d919fe214b, []int{6}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

func init() {
	proto.RegisterEnum("cac.store.v1.Partition", Partition_name, Partition_value)
	proto.RegisterType((*GetSaltRequest)(nil), "cac.store.v1.GetSaltRequest")
	proto.RegisterType((*GetSaltResponse)(nil), "cac.store.v1.GetSaltResponse")
	proto.RegisterType((*GetRequest)(nil), "cac.store.v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "cac.store.v1.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "cac.store.v1.PutRequest")
	proto.RegisterType((*PutHeader)(nil), "cac.store.v1.PutHeader")
	proto.RegisterType((*PutResponse)(nil), "cac.store.v1.PutResponse")
}

func init() { proto.RegisterFile("pkg/store/pb/store.proto", fileDescriptor_80e9d5d919fe214b) }

var fileDescriptor_80e9d5d919fe214b = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xdf, 0x6f, 0x93, 0x40,
	0x1c, 0x2f, 0xeb, 0x86, 0xf6, 0xdb, 0xa5, 0x23, 0xa7, 0x53, 0x66, 0x34, 0x51, 0xa2, 0xc9, 0x62,
	0x22, 0xb8, 0xaa, 0x6f, 0xbe, 0x8c, 0xd9, 0x16, 0xa2, 0x32, 0x02, 0xf4, 0xc5, 0xc4, 0x2c, 0x07,
	0x5c, 0x3a, 0xd2, 0xca, 0x21, 0x77, 0x58, 0xfb, 0x37, 0xfa, 0x4f, 0x19, 0x8e, 0x5f, 0xad, 0xd5,
	0x37, 0xdf, 0xbe, 0xf9, 0x7e, 0x7e, 0xf1, 0xe1, 0xee, 0x40, 0xcd, 0x96, 0x0b, 0x83, 0x71, 0x9a,
	0x13, 0x23, 0x0b, 0xab, 0x41, 0xcf, 0x72, 0xca, 0x29, 0x3a, 0x8e, 0x70, 0xa4, 0x57, 0x8b, 0x1f,
	0x17, 0x9a, 0x02, 0xa3, 0x19, 0xe1, 0x3e, 0x5e, 0x71, 0x8f, 0x7c, 0x2f, 0x08, 0xe3, 0xda, 0x0b,
	0x38, 0x69, 0x37, 0x2c, 0xa3, 0x29, 0x23, 0x08, 0xc1, 0x21, 0xc3, 0x2b, 0xae, 0x4a, 0x4f, 0xa5,
	0xf3, 0x63, 0x4f, 0xcc, 0xda, 0x1c, 0x60, 0x46, 0x1a, 0x11, 0x7a, 0x07, 0x83, 0x0c, 0xe7, 0x3c,
	0xe1, 0x09, 0x4d, 0x05, 0x6d, 0x34, 0x7e, 0xa8, 0x6f, 0x07, 0xe9, 0x6e, 0x03, 0x7b, 0x1d, 0x13,
	0x29, 0xd0, 0x5f, 0x92, 0x8d, 0x7a, 0x20, 0x7c, 0xcb, 0x51, 0x7b, 0x06, 0x43, 0x61, 0xdb, 0x25,
	0xc7, 0x98, 0xe3, 0x26, 0xb9, 0x9c, 0xb5, 0xaf, 0x00, 0x6e, 0xd1, 0x26, 0x5f, 0x80, 0x7c, 0x4b,
	0x70, 0x4c, 0x72, 0xc1, 0x19, 0xee, 0xc5, 0x16, 0xdc, 0x12, 0xb0, 0xd5, 0xf3, 0x6a, 0x22, 0xba,
	0x5f, 0x9b, 0x8a, 0x58, 0xab, 0x57, 0xd9, 0x9a, 0x32, 0x1c, 0x86, 0x34, 0xde, 0x68, 0x01, 0x0c,
	0x5a, 0xd1, 0xff, 0xeb, 0xf5, 0x1c, 0x86, 0xe2, 0xa3, 0xeb, 0x5e, 0xa7, 0x20, 0x27, 0xec, 0x26,
	0x25, 0x6b, 0x61, 0x7a, 0xd7, 0x3b, 0x4a, 0x98, 0x43, 0xd6, 0x2f, 0x17, 0x30, 0x68, 0xfd, 0xd0,
	0x19, 0x9c, 0xba, 0x97, 0x5e, 0x60, 0x07, 0xf6, 0xb5, 0x73, 0x33, 0x77, 0x7c, 0x77, 0x72, 0x65,
	0x4f, 0xed, 0xc9, 0x07, 0xa5, 0x87, 0xee, 0xc1, 0x49, 0x07, 0x5d, 0x59, 0x73, 0xe7, 0xa3, 0x22,
	0xa1, 0x07, 0x80, 0xba, 0xe5, 0xe7, 0x4b, 0xc7, 0x9e, 0x4e, 0xfc, 0x40, 0x39, 0x40, 0x08, 0x46,
	0xdd, 0xde, 0xfc, 0x74, 0x6d, 0x2a, 0xfd, 0xf1, 0x2f, 0x09, 0x8e, 0xfc, 0xb2, 0x02, 0x9a, 0xc2,
	0x9d, 0xfa, 0xb8, 0xd1, 0xe3, 0xdd, 0x66, 0xbb, 0xf7, 0xe2, 0xd1, 0x93, 0x7f, 0xa0, 0x75, 0xa3,
	0xf7, 0xd0, 0x9f, 0x11, 0x8e, 0xd4, 0x3d, 0x56, 0xa3, 0x3f, 0xfb, 0x0b, 0x52, 0x69, 0x5f, 0x4b,
	0xa5, 0xda, 0x2d, 0xf6, 0xd4, 0xdd, 0x31, 0xff, 0xa9, 0xde, 0xfa, 0x97, 0xe7, 0x92, 0xf9, 0xf6,
	0xcb, 0x78, 0x91, 0xf0, 0xdb, 0x22, 0xd4, 0x23, 0xfa, 0xcd, 0x58, 0x16, 0x98, 0xe1, 0xfc, 0x15,
	0xc3, 0x69, 0x1c, 0xd2, 0x9f, 0x06, 0x8e, 0x22, 0xb2, 0x22, 0x39, 0xe6, 0x34, 0x37, 0xb6, 0x1f,
	0x45, 0x28, 0x8b, 0xf7, 0xf0, 0xe6, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x9a, 0xda, 0xa8,
	0x2b, 0x03, 0x00, 0x00,
}
