// Package cac.store.v1 defines the gRPC wire protocol for the
// store-ctl daemon. Clients (manifest-ctl, cache-ctl origin) talk to
// store-ctl through this interface and never touch the underlying
// filesystem or object storage directly.
//
// The service is deliberately small: AdmitWrite fixes an ingest to one
// generation and salt, Get streams bytes out, and Put streams bytes in.
//
// Put is client-streaming with a header-first convention: the first
// PutRequest MUST carry a PutHeader (partition + client-computed key +
// admitted generation + optional size); subsequent PutRequests carry raw
// bytes. The server may SendAndClose early with is_new=false if a matching
// object already exists.
//
// Get is server-streaming: one GetRequest produces one or more
// GetResponse messages with byte chunks, or a NOT_FOUND status on miss.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pkg/store/pb/store.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Store_AdmitWrite_FullMethodName = "/cac.store.v1.Store/AdmitWrite"
	Store_Get_FullMethodName        = "/cac.store.v1.Store/Get"
	Store_Put_FullMethodName        = "/cac.store.v1.Store/Put"
)

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreClient interface {
	// AdmitWrite returns the generation and opaque salt shared by every
	// chunk and the final manifest of one ingest.
	AdmitWrite(ctx context.Context, in *AdmitWriteRequest, opts ...grpc.CallOption) (*AdmitWriteResponse, error)
	// Get streams an object's bytes back to the caller. On miss,
	// the server returns NOT_FOUND (no stream payload). On hit, one
	// or more data messages form the full object in order.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error)
	// Put streams an object from the caller. The first message MUST
	// be a PutHeader carrying partition + client-computed key,
	// generation, and optional payload size.
	// Subsequent messages carry raw byte chunks. The server may
	// SendAndClose early with is_new=false if the key already
	// exists. Otherwise the server streams data into the backend's
	// generation-bound handle and optionally re-hashes it.
	Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, PutResponse], error)
}

type storeClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreClient(cc grpc.ClientConnInterface) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) AdmitWrite(ctx context.Context, in *AdmitWriteRequest, opts ...grpc.CallOption) (*AdmitWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdmitWriteResponse)
	err := c.cc.Invoke(ctx, Store_AdmitWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Store_ServiceDesc.Streams[0], Store_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, GetResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Store_GetClient = grpc.ServerStreamingClient[GetResponse]

func (c *storeClient) Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, PutResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Store_ServiceDesc.Streams[1], Store_Put_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutRequest, PutResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Store_PutClient = grpc.ClientStreamingClient[PutRequest, PutResponse]

// StoreServer is the server API for Store service.
// All implementations must embed UnimplementedStoreServer
// for forward compatibility.
type StoreServer interface {
	// AdmitWrite returns the generation and opaque salt shared by every
	// chunk and the final manifest of one ingest.
	AdmitWrite(context.Context, *AdmitWriteRequest) (*AdmitWriteResponse, error)
	// Get streams an object's bytes back to the caller. On miss,
	// the server returns NOT_FOUND (no stream payload). On hit, one
	// or more data messages form the full object in order.
	Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error
	// Put streams an object from the caller. The first message MUST
	// be a PutHeader carrying partition + client-computed key,
	// generation, and optional payload size.
	// Subsequent messages carry raw byte chunks. The server may
	// SendAndClose early with is_new=false if the key already
	// exists. Otherwise the server streams data into the backend's
	// generation-bound handle and optionally re-hashes it.
	Put(grpc.ClientStreamingServer[PutRequest, PutResponse]) error
	mustEmbedUnimplementedStoreServer()
}

// UnimplementedStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServer struct{}

func (UnimplementedStoreServer) AdmitWrite(context.Context, *AdmitWriteRequest) (*AdmitWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdmitWrite not implemented")
}
func (UnimplementedStoreServer) Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStoreServer) Put(grpc.ClientStreamingServer[PutRequest, PutResponse]) error {
	return status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedStoreServer) mustEmbedUnimplementedStoreServer() {}
func (UnimplementedStoreServer) testEmbeddedByValue()               {}

// UnsafeStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServer will
// result in compilation errors.
type UnsafeStoreServer interface {
	mustEmbedUnimplementedStoreServer()
}

func RegisterStoreServer(s grpc.ServiceRegistrar, srv StoreServer) {
	// If the following call panics, it indicates UnimplementedStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Store_ServiceDesc, srv)
}

func _Store_AdmitWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmitWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).AdmitWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_AdmitWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).AdmitWrite(ctx, req.(*AdmitWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServer).Get(m, &grpc.GenericServerStream[GetRequest, GetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Store_GetServer = grpc.ServerStreamingServer[GetResponse]

func _Store_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServer).Put(&grpc.GenericServerStream[PutRequest, PutResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Store_PutServer = grpc.ClientStreamingServer[PutRequest, PutResponse]

// Store_ServiceDesc is the grpc.ServiceDesc for Store service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Store_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cac.store.v1.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdmitWrite",
			Handler:    _Store_AdmitWrite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _Store_Get_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Put",
			Handler:       _Store_Put_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/store/pb/store.proto",
}
